---
- name: install apache2 in ubuntu
  apt: name={{ item }} state=present update_cache=yes
  with_items:
        - apache2
        - mysql-server
        - php-mysql
        - php
        - libapache2-mod-php
        - php-mcrypt
- name: Restart the apache2
  service: name={{ service }} state=restarted
- name: Add the Datadog APT key
  apt_key: keyserver=keyserver.ubuntu.com id=C7A7DA52

- name: Add the Datadog source to the APT source list
  apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present

- name: Install Datadog agent
  apt: name={{item}} state=present update_cache=yes
  with_items:
   - datadog-agent
